version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: servora-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine

    container_name: servora-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  auth-service:
    build:
      context: ./services/auth-service

    container_name: auth-service

    restart: unless-stopped

    ports:
      - "8001:8001"

    depends_on:
      - mongodb
      - redis

    environment:
      PORT: 8001
      MONGO_URI: mongodb://admin:password@mongodb:27017/authdb?authSource=admin

  user-service:
    build:
      context: ./services/user-service

    container_name: user-service

    restart: unless-stopped

    ports:
      - "8002:8002"

    depends_on:
      - mongodb
      - redis

    environment:
      PORT: 8002
      MONGO_URI: mongodb://admin:password@mongodb:27017/userdb?authSource=admin

  api-gateway:
    build:
      context: ./api-gateway

    container_name: api-gateway

    restart: unless-stopped

    ports:
      - "8000:8000"

    depends_on:
      - auth-service
      - user-service

    environment:
      PORT: 8000

volumes:
  mongo_data:
  redis_data:
